[versions]
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
library = "2.0.1"
multidex = "2.0.1"
recyclerview = "1.4.0"
palette = "1.0.0"
commonsIo = "2.21.0"
gson = "2.13.2"
okhttp = "5.3.2"
picasso = "2.8"

firebaseAnalytics = "23.0.0"
firebaseBom = "34.6.0"
firebaseInappmessagingDisplay = "22.0.2"
internetSpeedTesting = "1.0.1"

scytale = "1.0.1"

onesignal = "5.4.1"

media3Exoplayer = "1.9.0-alpha01"
mediarouter = "1.8.1"
cast = "22.2.0"

youtubePlayer = "13.0.0"

admobAds = "24.8.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
library = { module = "com.github.nemosofts:material", version.ref = "library" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "palette" }

recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-inappmessaging-display = { module = "com.google.firebase:firebase-inappmessaging-display", version.ref = "firebaseInappmessagingDisplay" }
scytale = { module = "com.yakivmospan:scytale", version.ref = "scytale" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
internet-speed-testing = { module = "com.github.oatrice:internet-speed-testing", version.ref = "internetSpeedTesting" }

exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3Exoplayer"}
media3-datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3Exoplayer" }
exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3Exoplayer" }
exoplayer-smoothstreaming = { module = "androidx.media3:media3-exoplayer-smoothstreaming", version.ref = "media3Exoplayer"}
exoplayer-rtsp = { module = "androidx.media3:media3-exoplayer-rtsp", version.ref = "media3Exoplayer" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Exoplayer" }
media3-decoder = { module = "androidx.media3:media3-decoder", version.ref = "media3Exoplayer" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Exoplayer" }
media3-container = { module = "androidx.media3:media3-container", version.ref = "media3Exoplayer" }
media3-extractor = { module = "androidx.media3:media3-extractor", version.ref = "media3Exoplayer" }

mediarouter = { module = "androidx.mediarouter:mediarouter", version.ref = "mediarouter"}
cast = { module = "com.google.android.gms:play-services-cast-framework", version.ref = "cast"}

youtubeplayer-core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "youtubePlayer" }
youtubeplayer-ui = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:custom-ui", version.ref = "youtubePlayer" }

oneSignal = { module = "com.onesignal:OneSignal", version.ref = "onesignal" }

admob = { module = "com.google.android.gms:play-services-ads", version.ref = "admobAds" }

[bundles]
nemosofts = [
    "appcompat",
    "material",
    "constraintlayout",
    "library"
]
network-security = [
    "gson",
    "okhttp",
    "okhttp-interceptor",
    "picasso",
    "internet-speed-testing"
]
firebase = [
    "firebase-analytics",
    "firebase-inappmessaging-display"
]
youtubeplayer = [
    "youtubeplayer-core",
    "youtubeplayer-ui"
]
media3 = [
    "media3-session",
    "media3-datasource",
    "media3-decoder",
    "media3-common",
    "media3-container",
    "media3-extractor",
    "mediarouter",
    "cast"
]
exoplayer = [
    "exoplayer-dash",
    "exoplayer-hls",
    "exoplayer-smoothstreaming",
    "exoplayer-rtsp"
]